#!/bin/bash

#SBATCH --job-name=dummy_job
#SBATCH --account=project_462000353
#SBATCH --partition=debug
#SBATCH --time=00:01:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=slurm-logs/array_%A_%a.out
#SBATCH --error=slurm-logs/array_%A_%a.err
#SBATCH --array=0

# Mail sending / MTA doesn't seem to be enabled on LUMI. If it were, these can
# be used to send mail on different job status:

# #SBATCH --mail-user=<your_email>
# #SBATCH --mail-type=ALL

# If run without sbatch, invoke here
if [ -z "$SLURM_JOB_ID" ]; then
    sbatch "$0" "$@"
    exit
fi

# See http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail

rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
rm -f "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.err" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.err"
ln -s "array_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.out" "slurm-logs/current_${SLURM_JOB_NAME}_${SLURM_ARRAY_TASK_ID}.out"

# read -r SOME_VARIABLE < <(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" files.txt)

SOME_VARIABLE="Hello, World!"

sleep 10

echo "$SOME_VARIABLE"

sacct -o jobid,elapsed -j "${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}"

wait
